services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=development
    depends_on:
      - redis
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: php /var/www/html/bin/worker.php
    volumes:
      - .:/var/www/html
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge